import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import LoginButton from "./components/LoginButton";
import { redirect } from "next/navigation";
import { LogoSection } from "./components/LogoSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <header className="my-4 flex justify-between text-xl font-bold items-center p-4 gap-4 h-16">
            
            <LogoSection />

            <div>
              <LoginButton />
            </div>
          </header>

          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
